stages:
  data_ingestion:
    cmd: python src/malaria/e_pipeline/stg_01_data_ingestion.py
    deps:
      - src/malaria/e_pipeline/stg_01_data_ingestion.py
      - config/config.yaml
    outs:
      - artifacts/data_ingestion/Chicken-fecal-images

  base_model:
    cmd: python src/malaria/e_pipeline/stg_02_base_model.py
    deps:
      - src/malaria/e_pipeline/stg_02_base_model.py
      - config/config.yaml
    params:
      - IMAGE_SIZE
      - INCLUDE_TOP
      - CLASSES
      - WEIGHTS
      - LEARNING_RATE
    outs:
      - artifacts/base_model

  training:
    cmd: python src/malaria/e_pipeline/stg_03_training.py
    deps:
      - src/malaria/e_pipeline/stg_03_training.py
      - src/malaria/d_components/callbacks.py
      - config/config.yaml
      - artifacts/data_ingestion/Chicken-fecal-images
      - artifacts/base_model
    params:
      - IMAGE_SIZE
      - EPOCHS
      - BATCH_SIZE
      - AUGMENTATION
    outs:
      - artifacts/trained_model/model.h5

  evaluation:
    cmd: python src/malaria/e_pipeline/stg_04_evaluation.py
    deps:
      - src/malaria/e_pipeline/stg_04_evaluation.py
      - config/config.yaml
      - artifacts/data_ingestion/Chicken-fecal-images
      - artifacts/trained_model/model.h5
    params:
      - IMAGE_SIZE
      - BATCH_SIZE
    metrics:
      - scores.json:
          cache: false
